docs: contributing link fix
ory/meta pull request #63
Opened 2020-11-19 12:40 UTC by vinckr

There is still an error in
Line 163 the link to /docs/README.md
is broken (which I put in there btw.)

I tried to use (../../README.md) to make it work, but it does not and I dont know why.

2020-11-19 12:40 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ory/meta?pullRequest=63) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ory/meta?pullRequest=63) before we can accept your contribution.<br/><hr/>**vinckr** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ory/meta?pullRequest=63) it.</sub>

2020-11-19 12:41 UTC, vinckr commented on CONTRIBUTING.md
>  For further instructions please head over to [docs/README.md](docs/README.md).
This is broken, how can we fix this that it works with the script?
Or just leave out the link?

2020-11-19 13:27 UTC, vinckr commented
@zepatrik 
I would do the sidebar changes, when this PR is good. 
I dont know why the cla check fails :/

2020-11-19 13:30 UTC, zepatrik commented
`../../README.md` is outside of the docusaurus project so it can not be resolved.

2020-11-19 13:34 UTC, zepatrik requested changes

2020-11-19 13:34 UTC, zepatrik commented on CONTRIBUTING.md
> +Documentation resides in the project's docs folder. Generate API and
```suggestion
Documentation resides in the project's `docs` folder. Generate API and
```

2020-11-19 13:34 UTC, zepatrik commented on CONTRIBUTING.md
> +[docs/README.md](ttps://github.com/ory/{{Project}}/blob/master/README.md).
```suggestion
[docs/README.md](ttps://github.com/ory/{{Project}}/blob/master/docs/README.md).
```

2020-11-19 13:34 UTC, zepatrik commented on CONTRIBUTING.md
> +[list of good first issues](https://github.com/ory/{{Project}/labels/good%20first%20issue).
This looks wrong
```suggestion
[list of good first issues](https://github.com/ory/{{Project}}/labels/good%20first%20issue).
```

2020-11-19 15:24 UTC, aeneasr commented on CONTRIBUTING.md
> +Documentation resides in the project's `docs` folder. Generate API and
Why not link this like you have done below?

2020-11-19 15:24 UTC, aeneasr commented on CONTRIBUTING.md
> +- [Contributing to ORY {{Project}}](#contributing-to-ory-project)
Please revert this

2020-11-19 17:20 UTC, vinckr commented
hm when i `npm run format` 
it always adds 
- [Contributing to ORY {{Project}}](#contributing-to-ory-project)
to the TOC. 
when I dont do it, the format check fails :/.

2020-11-20 11:56 UTC, zepatrik commented
Does not do that for me :shrug:

2020-11-20 12:19 UTC, merged

2020-11-20 14:25 UTC, aeneasr commented
@vinckr this is the wrong file. The changes need to be done here: https://github.com/ory/meta/blob/master/templates/repository/common/CONTRIBUTING.md