fix: discussions-link sync
ory/meta pull request #87
Opened 2021-02-12 11:14 UTC by vinckr

Closes https://github.com/ory/meta/issues/85

As discussed in the issue a separate variable for the meta/discussions has been implemented.

A local test with the following testscript produced the desired result: 
Tested with "kratos" and "kratos-selfservice-ui-react-native"

```

#!/bin/bash

set -Eexuo pipefail

    humanName="kratos-selfservice-ui-react-native"
    project=ory/kratos-selfservice-ui-react-native
    discussions="https://github.com/$project/discussions"
    metaDiscussions="https://github.com/meta/discussions"

    for f in $(find "CONTRIBUTING.md" -type f -print); do
        if [[ "$project" = "ory/hydra" || $project = "ory/kratos" || $project = "ory/oathkeeper" || $project = "ory/keto" ]]; then
          env -i DISCUSSIONS="$discussions" REPOSITORY="$project" PROJECT="$humanName" /bin/bash -c "envsubst < \"$f\" | sponge \"$f\""
        else
          env -i DISCUSSIONS="$metaDiscussions" REPOSITORY="$project" PROJECT="$humanName" /bin/bash -c "envsubst < \"$f\" | sponge \"$f\""
        fi
    done
```

2021-02-16 14:32 UTC, aeneasr requested changes
The changes should not have any effect. `DISCUSSIONS="$metaDiscussions"` is simply substituted with `DISCUSSIONS="https://github.com/ory/meta/discussions"` which is what we had before.

Have you tested this?

2021-02-17 17:07 UTC, vinckr commented
The problem is that [in the CI for example ](https://github.com/ory/meta/runs/1707608653?check_suite_focus=true)it runs like so:
```
+ sync /tmp/tmp.FZkLPxIAOj master library 'Hydra Login, Logout And Consent Node Example' ory/hydra-login-consent-node
++ dirname scripts/sync.sh
+ cd scripts/..
+ workdir=/tmp/tmp.FZkLPxIAOj
+ branch=master
+ type=library
+ humanName='Hydra Login, Logout And Consent Node Example'
+ project=ory/hydra-login-consent-node
+ discussions=https://github.com/ory/hydra-login-consent-node/discussions
```

This does not happen locally. 
I believe the problem is that it first substitutes the env vars and then does the check:

```
+ for f in $(find "$workdir/.github/ISSUE_TEMPLATE" "$workdir/.github/pull_request_template.md" "$workdir/CONTRIBUTING.md" "$workdir/SECURITY.md" "$workdir/CODE_OF_CONDUCT.md" "$workdir/LICENSE" -type f -print)
+ [[ ory/hydra-login-consent-node = \o\r\y\/\h\y\d\r\a ]]
+ [[ ory/hydra-login-consent-node = \o\r\y\/\k\r\a\t\o\s ]]
+ [[ ory/hydra-login-consent-node = \o\r\y\/\o\a\t\h\k\e\e\p\e\r ]]
+ [[ ory/hydra-login-consent-node = \o\r\y\/\k\e\t\o ]]
+ env -i DISCUSSIONS=https://github.com/ory/meta/discussions REPOSITORY=ory/hydra-login-consent-node 'PROJECT=Hydra Login, Logout And Consent Node Example' /bin/bash -c 'envsubst < "/tmp/tmp.FZkLPxIAOj/.github/ISSUE_TEMPLATE/feature_request.md" | sponge "/tmp/tmp.FZkLPxIAOj/.github/ISSUE_TEMPLATE/feature_request.md"'

```

It works like intended here, but `DISCUSSIONS=https://github.com/ory/meta/discussions` gets overwritten with the previous `discussions=https://github.com/ory/hydra-login-consent-node/discussions`

Again this is not how it works when I test it locally. 

My fix would be now to introduce `metaDiscussions` since then it would not get overwritten and still get correctly replaced in the later part. The normal `discussions` works as before for all GH discussions outside of /meta. 

Locally it works (just like it did before), I dont know how or why it runs differently in the CI and I cant test it there( or can I?). 

This was my thought process behind the change, let me know if it makes sense at all @aeneasr.

2021-02-18 14:11 UTC, aeneasr commented on scripts/sync.sh
> +          env -i DISCUSSIONS="$metaDiscussions" REPOSITORY="$project" PROJECT="$humanName" /bin/bash -c "envsubst < \"$f\" | sponge \"$f\""
What about

```suggestion
          env -i 'DISCUSSIONS="https://github.com/ory/meta/discussions"' REPOSITORY="$project" PROJECT="$humanName" /bin/bash -c "envsubst < \"$f\" | sponge \"$f\""
```

2021-02-18 14:13 UTC, aeneasr commented
I don't understand, the replacement is working fine: https://github.com/ory/kratos-selfservice-ui-node/blob/master/CONTRIBUTING.md#introduction

If I click on `ORY Kratos SelfService UI Node Example Discussions` I am landing at meta/discussions

What problem are you trying to solve?

2021-02-18 14:49 UTC, vinckr commented
Well when I opened the issue this was not the case. 
It seems the repo template was only updated just a day after I opened the issue. 
So nevermind then....

2021-02-18 14:49 UTC, closed without merging